variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - package

build:
  image: openjdk:11
  stage: build
  allow_failure: false
  tags:
    - docker
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/err0agent-*-fat.jar
  only:
    refs:
      - develop
      - master

package-develop:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo -n f3ea7578-2938-4d78-b745-22a1d13b0e06 | docker login -u err0io --password-stdin
    - cp build/libs/err0agent-*-fat.jar docker/agent
  script:
    - docker build --no-cache docker/agent --tag err0_io:err0_agent --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag err0io/agent:develop
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push err0io/agent:develop
  allow_failure: false
  dependencies:
    - build
  only:
    refs:
      - develop

package-master:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo -n f3ea7578-2938-4d78-b745-22a1d13b0e06 | docker login -u err0io --password-stdin
    - cp build/libs/err0agent-*-fat.jar docker/agent
  script:
    - docker build --no-cache docker/agent --tag err0_io:err0_agent --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag err0io/agent:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push err0io/agent:latest
  allow_failure: false
  dependencies:
    - build
  only:
    refs:
      - master