== Building

To run your application, first head over to the `err0server` project where the database now lives and in that run:

```
err0server $ rm -rf .docker-build
err0server $ ./docker-start.sh
```

to start-up a local postgres on port 54321

edit the last part of ``build.gradle.kts`` to add a directory to scan
as the program arguments.

```
err0proto $ ./gradlew clean runShadow
```

to run the program with the arguments in the ``build.gradle.kts``.

=== Using on your project, doesn't need the database running...

Using the 'unit test' API provider you can get repeatable results with your project!

First - create a realm/application and an API token, donwload the token json and use as follows:

```
err0proto $ ./gradlew runShadow --args="--token tokens/err0-open-source-software-moodle-fcc1f565-0ff0-11ec-b8c2-a63d063ada96.json /your/local/path/to/your/local/git/repo"
```

This will communicate with ```err0server``` on localhost and import error
codes according to the server's policy for the application.

You should be able to test the result, find that it works, and commit the changes to your
repository so that your customers get better error reports and your log
files are more descriptive.