== What is err0?

err0 is a software observability foundation. 

Observability means to understand the internal state or condition of a system based only on knowledge of its external outputs.
The more observable a system is, the quicker you can navigate it and more accurately you can identified the problem back to its root cause.

Err0 is a game-changing solution which seamlessly transforms the observability level of any software.
With Err0, errors and exceptions are: uniquely identified (numbered), tracked, managed through the entire life-cycle of the software, and can be dynamically enriched.

See https://www.err0.io/

== What is required to test or use err0?

An account on the err0.io platform is required to use all the features of err0agent, but you can also use it without an err0.io account in fully stand-alone mode.

== What is the err0agent?

The err0agent is the agent that will parse the code, detect logs, errors and exceptions statement and apply the corresponding Management Policy, notably by inserting error codes. The agent is open-source as we wouldn't ourselves run anything in our CI/CD pipeline that we couldn't check.

== Which programming languages are supported by err0?

The err0agent supports: java, javascript, c#, python, php, go, typescript.

== Using err0agent

In stand-alone mode, you can use the err0agent jar to
manage error codes in your project!  This assumes that you have built the jar with ```gradlew build```...

Firstly: to insert codes into your project:

```
$ java -jar build/libs/err0agent-java_1_8-fat.jar --stand-alone --insert --git-dir <path/to/your/project>
```

after this step, err0agent will have modified your source
code to add unique error codes to your logs and exceptions or
errors.

Secondly: to check that there are no missing codes:

```
$ java -jar build/libs/err0agent-java_1_8-fat.jar --stand-alone --check --git-dir <path/to/your/project>
```

That's all!

When you're ready to use this in production why not create
an err0.io account, you can make a detailed configuration for the agent on our platform and of course manage knowledge around your error codes.