name: err0agent build pipeline

on:
  push:
    branches: [ "develop", "master" ]
    tags: '*'
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:

  err0-secret:
    runs-on: ubuntu-latest

    steps:
    - name: create token from secret
      run: |
          mkdir -p tokens
          echo "$SECRET" >> tokens/err0agent.json
          cat tokens/err0agent.json
      shell: bash
      env:
        SECRET: ${{secrets.ERR0_TOKEN}}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: err0agent-token
        path: |
          tokens/err0agent.json

  err0:
  
    runs-on: ubuntu-latest
    container: err0io/agent:latest
    needs: err0-secret
    
    steps:
    - uses: actions/checkout@v3
    - name: git fetch tags
      run: |
        git fetch --all --tags --force
    - uses: actions/download-artifact@v3.0.0
      with: 
        name: err0agent-token
        path: tokens
    - run: err0.sh --token tokens/err0agent.json --analyse --check .

  build:

    runs-on: ubuntu-latest
    needs: err0

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Create checksums
      run: |
       sha256sum build/libs/err0agent-java_1_8-fat.jar > build/libs/err0agent-java_1_8-fat.jar.sha256
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: err0agent-fat-jar
        path: |
          build/libs/err0agent-java_1_8-fat.jar
          build/libs/err0agent-java_1_8-fat.jar.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/libs/err0agent-java_1_8-fat.jar
          build/libs/err0agent-java_1_8-fat.jar.sha256

  package-develop:
  
    if: github.ref == 'refs/heads/develop'
  
    runs-on: ubuntu-latest
    needs: build
    
    container: docker:latest
    services:
      dind:
        image: docker:dind
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3.0.0
      with: 
        name: err0agent-fat-jar
        path: docker/agent
    - run: docker info
    - run: echo -n ${{ secrets.DOCKER_HUB_ERR0IO_PASSWORD }} | docker login -u err0io --password-stdin
    - run: docker buildx create --driver docker-container --use
    - run: docker buildx build --platform linux/amd64,linux/arm64 --no-cache docker/agent --tag err0io/agent:develop --push

  package-master:

    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: build

    container: docker:latest
    services:
      dind:
        image: docker:dind

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.0.0
        with:
          name: err0agent-fat-jar
          path: docker/agent
      - run: docker info
      - run: echo -n ${{ secrets.DOCKER_HUB_ERR0IO_PASSWORD }} | docker login -u err0io --password-stdin
      - run: docker buildx create --driver docker-container --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 --no-cache docker/agent --tag err0io/agent:latest --push

