name: err0agent build pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  err0:
  
    runs-on: ubuntu-latest
    container: err0io/agent:latest
    
    steps:
    - uses: actions/checkout@v3
    - run: err0.sh --token tokens/err0-err0-io-err0agent-dc4ccb4c-5da5-11ec-a0b8-4622287bbd85.json --analyse --check .

  build:

    runs-on: ubuntu-latest
    needs: err0

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: err0agent fat jar
        path: |
          build/libs/err0agent-*-fat.jar

  pacakge-develop-x64:
  
    runs-on: ubuntu-latest
    needs: build
    
    container: docker:latest
    services:
      dind:
        image: docker:dind
    
    steps:
    - uses: actions/checkout@v3
    - run: docker info
    - run: echo -n ${{ secrets.DOCKER_HUB_ERR0IO_PASSWORD }} | docker login -u err0io --password-stdin
    - run: cp build/libs/err0agent-*-fat.jar docker/agent
    - run: docker build --no-cache docker/agent --tag err0io/agent:develop
    - run: docker push err0io/agent:develop
